-- ============================================================================
--  Maren waitlist — Supabase schema
--  Run once in the Supabase SQL editor. Safe to re-run.
--
--  Security model: the browser holds only the publishable key, so it is
--  treated as untrusted. Nothing in here is readable from the client — the
--  waitlist table has RLS on with zero policies and all grants revoked, and
--  the analytics schema is not exposed by PostgREST at all. The only surface
--  the browser can reach is the four RPCs granted to `anon` at the bottom.
-- ============================================================================


-- ────────────────────────────────────────────────────────────────────────────
--  1. Waitlist
-- ────────────────────────────────────────────────────────────────────────────

create table if not exists public.waitlist (
  id            uuid primary key default gen_random_uuid(),
  -- Unguessable secret handed to the browser at step 1 and used to authorize
  -- the later patches. Never authorize a patch by email: anyone could then
  -- overwrite a stranger's row just by knowing their address.
  token         uuid   not null default gen_random_uuid(),
  signup_order  bigint generated by default as identity,
  email         text   not null unique,
  city          text,
  frustration   text,
  phone         text,
  dream_feature text,
  referral_code text   not null unique,
  referred_by   uuid   references public.waitlist(id) on delete set null,
  source        text,           -- hero | bottom | sticky
  visitor_id    uuid,           -- links this row to its pre-signup analytics
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create index if not exists waitlist_referred_by_idx on public.waitlist (referred_by);
create index if not exists waitlist_created_at_idx  on public.waitlist (created_at);
create index if not exists waitlist_token_idx       on public.waitlist (token);
create index if not exists waitlist_visitor_idx     on public.waitlist (visitor_id);

-- RLS on with NO policies = deny everything. The revoke matters too: Supabase
-- grants anon broad table privileges by default, and RLS alone would not stop
-- a role that still holds SELECT if a policy is ever added carelessly later.
alter table public.waitlist enable row level security;
revoke all on public.waitlist from anon, authenticated;


-- ────────────────────────────────────────────────────────────────────────────
--  2. Rate limiting (the RPCs are public write endpoints)
-- ────────────────────────────────────────────────────────────────────────────

create table if not exists public.rate_limit (
  bucket       text primary key,
  n            int not null default 0,
  window_start timestamptz not null default now()
);

alter table public.rate_limit enable row level security;
revoke all on public.rate_limit from anon, authenticated;

-- Real client IP, as forwarded by the Supabase edge. Returns null outside a
-- PostgREST request (e.g. when called from the SQL editor).
create or replace function public.client_ip()
returns text
language sql
stable
set search_path = public, pg_temp
as $$
  select nullif(
    btrim(split_part(
      coalesce(current_setting('request.headers', true)::json ->> 'x-forwarded-for', ''),
      ',', 1
    )),
    ''
  );
$$;

-- Fixed-window counter. Returns false once the bucket is over its limit.
create or replace function public.rl_check(p_bucket text, p_limit int, p_window interval)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_n int;
begin
  insert into public.rate_limit (bucket, n, window_start)
  values (p_bucket, 1, now())
  on conflict (bucket) do update set
    n = case when rate_limit.window_start < now() - p_window then 1
             else rate_limit.n + 1 end,
    window_start = case when rate_limit.window_start < now() - p_window then now()
                        else rate_limit.window_start end
  returning n into v_n;

  return v_n <= p_limit;
end;
$$;


-- ────────────────────────────────────────────────────────────────────────────
--  3. Analytics (private schema — PostgREST exposes only `public`)
-- ────────────────────────────────────────────────────────────────────────────

create schema if not exists analytics;

create table if not exists analytics.events (
  id           bigint generated by default as identity primary key,
  visitor_id   uuid  not null,                 -- random, localStorage, no PII
  session_id   uuid,                           -- per visit, sessionStorage
  waitlist_id  uuid references public.waitlist(id) on delete set null,
  name         text  not null,
  props        jsonb not null default '{}'::jsonb,
  path         text,
  referrer     text,
  utm_source   text,
  utm_medium   text,
  utm_campaign text,
  ref_code     text,
  created_at   timestamptz not null default now()
);

create index if not exists events_name_created_idx on analytics.events (name, created_at);
create index if not exists events_visitor_idx      on analytics.events (visitor_id);
create index if not exists events_waitlist_idx     on analytics.events (waitlist_id);

revoke all on schema analytics from anon, authenticated;


-- ────────────────────────────────────────────────────────────────────────────
--  4. Internal helpers (never exposed — see the revokes at the bottom)
-- ────────────────────────────────────────────────────────────────────────────

-- 7 chars from an alphabet with i/l/o/0/1 removed, so codes survive being read
-- aloud or retyped from a screenshot.
create or replace function public.gen_ref_code()
returns text
language sql
volatile
set search_path = public, pg_temp
as $$
  select string_agg(
    substr('abcdefghjkmnpqrstuvwxyz23456789', floor(random() * 31)::int + 1, 1),
    ''
  )
  from generate_series(1, 7);
$$;

-- The only shape ever returned to the browser. Deliberately excludes email,
-- phone, city and every other field belonging to a person.
create or replace function public.waitlist_payload(p_id uuid)
returns json
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select json_build_object(
    'token',         w.token,
    'referral_code', w.referral_code,
    'signup_order',  w.signup_order,
    'referrals',     r.n,
    -- Each referral is worth 25 places. This is a real queue rule: invites
    -- must be sent in this same order, or the number shown becomes a lie.
    'position',      greatest(1, w.signup_order - r.n * 25),
    'total',         (select count(*) from public.waitlist)
  )
  from public.waitlist w
  cross join lateral (
    select count(*)::int as n from public.waitlist x where x.referred_by = w.id
  ) r
  where w.id = p_id;
$$;


-- ────────────────────────────────────────────────────────────────────────────
--  5. Public RPCs
-- ────────────────────────────────────────────────────────────────────────────

-- Creates the row as soon as a valid email exists (step 1), so someone who
-- abandons at step 2 still leaves a usable record.
create or replace function public.join_waitlist(
  p_email   text,
  p_city    text default null,
  p_ref     text default null,
  p_source  text default 'hero',
  p_visitor uuid default null
)
returns json
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_email  text := lower(btrim(coalesce(p_email, '')));
  v_city   text := left(nullif(btrim(coalesce(p_city, '')), ''), 120);
  v_id     uuid;
  v_ref_id uuid;
begin
  -- The client-side regex is a UX affordance, not a control. Re-check here.
  if v_email !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'
     or length(v_email) > 254 then
    raise exception 'Please enter a valid email address.' using errcode = '22023';
  end if;

  -- Returning visitor: idempotent, and never rate limited — someone coming
  -- back to their own signup must not be turned away by a shared office IP.
  select id into v_id from public.waitlist where email = v_email;

  if v_id is null then
    if not public.rl_check('join:' || coalesce(public.client_ip(), 'unknown'),
                           10, interval '1 hour') then
      raise exception 'Too many signups from this network. Please try again later.'
        using errcode = '22023';
    end if;

    if p_ref is not null and length(btrim(p_ref)) between 4 and 16 then
      select id into v_ref_id
      from public.waitlist
      where referral_code = lower(btrim(p_ref));
    end if;

    -- Retry loop covers referral-code collisions and the race where two tabs
    -- submit the same email at once.
    for i in 1 .. 5 loop
      begin
        insert into public.waitlist (email, city, referral_code, referred_by, source, visitor_id)
        values (
          v_email,
          v_city,
          public.gen_ref_code(),
          v_ref_id,
          case when p_source in ('hero', 'bottom', 'sticky') then p_source else 'hero' end,
          p_visitor
        )
        returning id into v_id;
        exit;
      exception when unique_violation then
        select id into v_id from public.waitlist where email = v_email;
        if v_id is not null then exit; end if;
      end;
    end loop;

    if v_id is null then
      raise exception 'Could not join the waitlist. Please try again.' using errcode = '22023';
    end if;

  elsif v_city is not null then
    update public.waitlist
    set city = coalesce(city, v_city), updated_at = now()
    where id = v_id;
  end if;

  -- Back-stamp this visitor's earlier events, so the whole pre-signup session
  -- (which ads, which sections, how far they scrolled) attributes to the
  -- person it converted.
  if p_visitor is not null then
    update analytics.events
    set waitlist_id = v_id
    where visitor_id = p_visitor and waitlist_id is null;
  end if;

  return public.waitlist_payload(v_id);
end;
$$;

-- Patches the row identified by its token. Only non-empty arguments are
-- applied, so a later step can never blank a field an earlier one filled.
-- Called with no fields it just returns a fresh payload (used to refresh the
-- live position and referral count on the success screen).
create or replace function public.update_waitlist(
  p_token         uuid,
  p_city          text default null,
  p_frustration   text default null,
  p_phone         text default null,
  p_dream_feature text default null
)
returns json
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_id uuid;
begin
  select id into v_id from public.waitlist where token = p_token;
  if v_id is null then
    raise exception 'Unknown session.' using errcode = '22023';
  end if;

  -- Over-long input is truncated rather than rejected: losing the tail of an
  -- answer beats failing a write the user cannot see or retry.
  update public.waitlist set
    city          = coalesce(left(nullif(btrim(p_city), ''), 120), city),
    frustration   = coalesce(left(nullif(btrim(p_frustration), ''), 300), frustration),
    phone         = coalesce(left(nullif(btrim(p_phone), ''), 32), phone),
    dream_feature = coalesce(left(nullif(btrim(p_dream_feature), ''), 1000), dream_feature),
    updated_at    = now()
  where id = v_id;

  return public.waitlist_payload(v_id);
end;
$$;

-- Aggregates only. The page hides each number until it is meaningful, so
-- these are allowed to be zero.
create or replace function public.waitlist_stats()
returns json
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select json_build_object(
    'total', count(*),
    -- Day boundary in Charlotte's timezone, not UTC.
    'today', count(*) filter (
      where created_at >= date_trunc('day', now() at time zone 'America/New_York')
                          at time zone 'America/New_York'
    ),
    'city',      count(*) filter (where city ilike '%charlotte%'),
    'week',      count(*) filter (where created_at >= now() - interval '7 days'),
    'prev_week', count(*) filter (
      where created_at >= now() - interval '14 days'
        and created_at <  now() - interval '7 days'
    )
  )
  from public.waitlist;
$$;

-- Batched event ingest. Write-only from the browser's perspective: there is
-- no read path to analytics.events with a publishable key.
create or replace function public.track(
  p_visitor uuid,
  p_session uuid,
  p_events  jsonb,
  p_ctx     jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_wl uuid;
begin
  if p_visitor is null or jsonb_typeof(p_events) <> 'array' then return; end if;
  if jsonb_array_length(p_events) not between 1 and 50 then return; end if;

  -- Drop silently when over budget: analytics must never surface an error to
  -- a real user, and a bot gets no signal about the limit either.
  if not public.rl_check('track:' || coalesce(public.client_ip(), 'unknown'),
                         600, interval '1 hour') then
    return;
  end if;

  select id into v_wl from public.waitlist where visitor_id = p_visitor limit 1;

  insert into analytics.events (
    visitor_id, session_id, waitlist_id, name, props,
    path, referrer, utm_source, utm_medium, utm_campaign, ref_code
  )
  select
    p_visitor,
    p_session,
    v_wl,
    e ->> 'n',
    case
      when jsonb_typeof(e -> 'p') = 'object' and length((e -> 'p')::text) <= 2000
      then e -> 'p'
      else '{}'::jsonb
    end,
    left(p_ctx ->> 'path',         300),
    left(p_ctx ->> 'referrer',     500),
    left(p_ctx ->> 'utm_source',   100),
    left(p_ctx ->> 'utm_medium',   100),
    left(p_ctx ->> 'utm_campaign', 100),
    left(p_ctx ->> 'ref',           32)
  from jsonb_array_elements(p_events) e
  -- Allowlist. Without it a bot can invent event names and quietly poison
  -- every funnel number in the views below.
  where e ->> 'n' = any (array[
    'page_view', 'form_focus', 'email_invalid', 'email_valid',
    'step_view', 'chip_select', 'step_continue',
    'phone_submit', 'phone_skip', 'signup_complete',
    'share_copy', 'dream_send', 'dream_skip',
    'scroll_depth', 'section_view', 'carousel_swipe', 'exit'
  ]);
end;
$$;


-- ────────────────────────────────────────────────────────────────────────────
--  6. Analytics views — query these in the SQL editor
-- ────────────────────────────────────────────────────────────────────────────

-- Where do people leave?
drop view if exists analytics.funnel;
create view analytics.funnel as
with landed as (
  select count(distinct visitor_id)::numeric as n
  from analytics.events where name = 'page_view'
),
stages as (
  select 1 as ord, 'landed'       as stage, count(distinct visitor_id) as visitors from analytics.events where name = 'page_view'
  union all
  select 2, 'form_focus',   count(distinct visitor_id) from analytics.events where name = 'form_focus'
  union all
  select 3, 'email_valid',  count(distinct visitor_id) from analytics.events where name = 'email_valid'
  union all
  select 4, 'step2_viewed', count(distinct visitor_id) from analytics.events where name = 'step_view' and props ->> 'n' = '2'
  union all
  select 5, 'step3_viewed', count(distinct visitor_id) from analytics.events where name = 'step_view' and props ->> 'n' = '3'
  union all
  select 6, 'signup',       count(distinct visitor_id) from analytics.events where name = 'signup_complete'
)
select s.stage,
       s.visitors,
       round(100 * s.visitors / nullif(l.n, 0), 1) as pct_of_landed
from stages s cross join landed l
order by s.ord;

-- How far did each visitor get before giving up?
drop view if exists analytics.drop_off;
create view analytics.drop_off as
with per_visitor as (
  select visitor_id,
         max(case when name = 'step_view' and props ->> 'n' ~ '^[0-9]+$'
                  then (props ->> 'n')::int else 0 end) as last_step,
         bool_or(name = 'signup_complete') as converted
  from analytics.events
  group by visitor_id
)
select last_step,
       count(*)                        as visitors,
       count(*) filter (where converted) as converted
from per_visitor
group by last_step
order by last_step;

-- Which traffic actually converts?
drop view if exists analytics.sources;
create view analytics.sources as
select coalesce(
         utm_source,
         nullif(split_part(regexp_replace(referrer, '^https?://', ''), '/', 1), ''),
         'direct'
       ) as source,
       utm_medium,
       utm_campaign,
       count(distinct visitor_id)  as visitors,
       count(distinct waitlist_id) as signups,
       round(100.0 * count(distinct waitlist_id) / nullif(count(distinct visitor_id), 0), 1) as conv_pct
from analytics.events
group by 1, 2, 3
order by visitors desc;

-- Which of the three forms on the page does the work?
drop view if exists analytics.forms;
create view analytics.forms as
select coalesce(source, 'unknown') as form,
       count(*) as signups,
       count(*) filter (where phone is not null)         as gave_phone,
       count(*) filter (where frustration is not null)   as answered_q,
       count(*) filter (where dream_feature is not null) as wrote_dream
from public.waitlist
group by 1
order by signups desc;

-- Which pain point resonates? (the stored answer, not the click)
drop view if exists analytics.chips;
create view analytics.chips as
select frustration, count(*) as n
from public.waitlist
where frustration is not null
group by 1
order by n desc;

-- Last 30 days.
drop view if exists analytics.daily;
create view analytics.daily as
select d::date as day,
       (select count(distinct visitor_id) from analytics.events e
         where e.created_at >= d and e.created_at < d + interval '1 day') as visitors,
       (select count(*) from public.waitlist w
         where w.created_at >= d and w.created_at < d + interval '1 day') as signups
from generate_series(current_date - 29, current_date, interval '1 day') d
order by day desc;


-- ────────────────────────────────────────────────────────────────────────────
--  7. Grants — the entire public API surface
--
--  PostgREST only exposes functions the calling role may execute, so revoking
--  is what keeps the helpers invisible. The security definer RPCs still call
--  them fine: inside those, the effective user is the owner.
-- ────────────────────────────────────────────────────────────────────────────

revoke execute on function public.waitlist_payload(uuid)              from public, anon, authenticated;
revoke execute on function public.rl_check(text, int, interval)       from public, anon, authenticated;
revoke execute on function public.client_ip()                         from public, anon, authenticated;
revoke execute on function public.gen_ref_code()                      from public, anon, authenticated;

revoke execute on function public.join_waitlist(text, text, text, text, uuid)  from public;
revoke execute on function public.update_waitlist(uuid, text, text, text, text) from public;
revoke execute on function public.waitlist_stats()                              from public;
revoke execute on function public.track(uuid, uuid, jsonb, jsonb)               from public;

grant execute on function public.join_waitlist(text, text, text, text, uuid)   to anon, authenticated;
grant execute on function public.update_waitlist(uuid, text, text, text, text) to anon, authenticated;
grant execute on function public.waitlist_stats()                              to anon, authenticated;
grant execute on function public.track(uuid, uuid, jsonb, jsonb)               to anon, authenticated;
