/**
 * Terms of Use, as structured data rather than a wall of JSX — the copy is the
 * thing that changes, and this keeps an edit to one string.
 *
 * Bump LAST_UPDATED whenever the text below changes.
 */

export const LAST_UPDATED = "August 14, 2026";

export type TermsBlock =
  | { type: "p"; text: string }
  | { type: "ul"; items: string[] };

export type TermsSection = { heading: string; blocks: TermsBlock[] };

export const TERMS: TermsSection[] = [
  {
    "heading": "1. Acceptance of Terms",
    "blocks": [
      {
        "type": "p",
        "text": "By joining the Maren waitlist or using meetmaren.app (\"Service\"), you agree to these Terms of Use. If you do not agree, do not use the Service. Maren is operated by Maren (\"Company,\" \"we,\" \"us\"), a limited liability company based in Charlotte, North Carolina."
      }
    ]
  },
  {
    "heading": "2. Eligibility",
    "blocks": [
      {
        "type": "p",
        "text": "You must be at least 18 years old to use Maren. By joining the waitlist or creating an account, you represent that you are 18 or older and have the legal capacity to enter into these Terms."
      }
    ]
  },
  {
    "heading": "3. Service Description",
    "blocks": [
      {
        "type": "p",
        "text": "Maren is an AI-powered dating service that uses conversational profiling and machine learning to introduce users to potential matches. The Service currently operates as a waitlist. When launched, Maren will introduce you to one person at a time based on compatibility analysis. Maren does not guarantee any particular outcome, including romantic connections, dates, or relationships."
      }
    ]
  },
  {
    "heading": "4. Waitlist & Early Access",
    "blocks": [
      {
        "type": "p",
        "text": "Joining the waitlist does not guarantee access to the Service. Early access is offered at our discretion based on waitlist position, referral activity, location, and other factors. We reserve the right to modify, pause, or discontinue the waitlist at any time."
      }
    ]
  },
  {
    "heading": "5. Your Account & Data",
    "blocks": [
      {
        "type": "p",
        "text": "When you join the waitlist, you provide us with your email address and optionally your phone number and city. You agree to provide accurate information. We use this data to:"
      },
      {
        "type": "ul",
        "items": [
          "Manage your waitlist position and communicate updates",
          "Send you one SMS notification when access is available (if you provide a phone number)",
          "Improve and develop the Service",
          "Track anonymous, aggregated usage analytics"
        ]
      },
      {
        "type": "p",
        "text": "We do not sell your personal data to third parties. We do not send marketing emails or SMS newsletters unless you explicitly opt in."
      }
    ]
  },
  {
    "heading": "6. AI-Powered Matching",
    "blocks": [
      {
        "type": "p",
        "text": "Maren uses artificial intelligence to analyze conversational input and generate match recommendations. By using the Service, you acknowledge that:"
      },
      {
        "type": "ul",
        "items": [
          "Match recommendations are generated by AI and are not guarantees of compatibility",
          "Your conversational input may be processed by AI systems to improve matching quality",
          "AI-generated match explanations are algorithmic assessments, not professional advice",
          "You are responsible for your own decisions regarding any introductions made through the Service"
        ]
      }
    ]
  },
  {
    "heading": "7. User Conduct",
    "blocks": [
      {
        "type": "p",
        "text": "You agree not to:"
      },
      {
        "type": "ul",
        "items": [
          "Provide false or misleading information during signup or profiling",
          "Use the Service for any unlawful purpose or to harass, abuse, or harm others",
          "Attempt to manipulate the waitlist position, referral system, or matching algorithm",
          "Create multiple accounts or use automated tools to interact with the Service",
          "Reverse-engineer, decompile, or attempt to extract the source code or algorithms of the Service"
        ]
      },
      {
        "type": "p",
        "text": "We reserve the right to remove users who violate these terms without notice."
      }
    ]
  },
  {
    "heading": "8. Referral Program",
    "blocks": [
      {
        "type": "p",
        "text": "The waitlist referral program allows you to share a unique link. When someone joins through your link, your waitlist position may be adjusted. Referral benefits (including priority access, early invites, and founding member status) are offered at our discretion and may be modified or discontinued at any time. Fraudulent or manipulated referrals may result in removal from the waitlist."
      }
    ]
  },
  {
    "heading": "9. Intellectual Property",
    "blocks": [
      {
        "type": "p",
        "text": "All content, design, branding, algorithms, and technology associated with Maren are owned by Maren. You may not copy, modify, distribute, or create derivative works from any part of the Service without written permission. \"Maren\" and the Maren logo are trademarks of Maren."
      }
    ]
  },
  {
    "heading": "10. Disclaimers",
    "blocks": [
      {
        "type": "p",
        "text": "The Service is provided \"as is\" and \"as available.\" We make no warranties, express or implied, regarding the Service's reliability, accuracy, or fitness for a particular purpose. We do not conduct background checks on users. You are solely responsible for your safety when meeting anyone introduced through the Service."
      }
    ]
  },
  {
    "heading": "11. Limitation of Liability",
    "blocks": [
      {
        "type": "p",
        "text": "To the maximum extent permitted by law, Maren shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of or inability to use the Service, including but not limited to damages from personal interactions with other users, emotional distress, or loss of data."
      }
    ]
  },
  {
    "heading": "12. Termination",
    "blocks": [
      {
        "type": "p",
        "text": "We may suspend or terminate your access to the Service at any time, for any reason, without prior notice."
      }
    ]
  },
  {
    "heading": "13. Changes to These Terms",
    "blocks": [
      {
        "type": "p",
        "text": "We may update these Terms at any time. If we make material changes, we will notify you via the email address associated with your waitlist registration. Continued use of the Service after changes constitutes acceptance of the updated Terms."
      }
    ]
  },
  {
    "heading": "14. Governing Law",
    "blocks": [
      {
        "type": "p",
        "text": "These Terms are governed by the laws of the State of North Carolina, without regard to conflict of law principles. Any disputes arising under these Terms shall be resolved in the courts of Mecklenburg County, North Carolina."
      }
    ]
  }
];
